-- CreateTable
CREATE TABLE `HangMan` (
    `Id` INTEGER NOT NULL AUTO_INCREMENT,
    `WordId` INTEGER NOT NULL,
    `UserId` INTEGER NULL,
    `Correct` VARCHAR(191) NOT NULL,
    `Wrong` VARCHAR(191) NOT NULL,
    `Win` BOOLEAN NOT NULL DEFAULT false,
    `CreatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UpdatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`Id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `HangMan` ADD CONSTRAINT `HangMan_UserId_fkey` FOREIGN KEY (`UserId`) REFERENCES `User`(`Id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `HangMan` ADD CONSTRAINT `HangMan_WordId_fkey` FOREIGN KEY (`WordId`) REFERENCES `Word`(`Id`) ON DELETE RESTRICT ON UPDATE CASCADE;
